### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by lualbertovargas** [ArkhipenkaPiotr/thanos_snap_effect#5]
It's not really a problem, but it would help 10x the time if you put this snippet in installation in pub dev or as important

IMPORTANT: This package uses the custom fragment shader, so you should include the shader file in your pubspec.yaml file.

flutter:
 shaders:
 - packages/thanos_snap_effect/shader/thanos_snap_effect.glsl

**Comment by ArkhipenkaPiotr** [comment]
Hi @lualbertovargas. Unfortunately, there is no possibility to customize the "Installation" tab at this point. It's a known issue for the pub.dev contributors. https://github.com/dart-lang/pub-dev/issues/2967
For now, I suggest closing this issue and reopening it when the updates come

**Comment by lualbertovargas** [comment]
You're right, that's what we're missing in pub.dev, perfect, good job.
