### ISSUE TITLE
White background color issue

### ISSUE THREAD

**Issue by iamnicat** [ArkhipenkaPiotr/thanos_snap_effect#8]
When the item's color is white, it changes to black after the animation finishes.
it only appears in real devices. in simulator is okay

https://github.com/user-attachments/assets/47bf7ca3-ad92-4836-9de6-18d2342649e1

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B2091 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (5 available)
    ! Error: Browsing on the local area network for Nijat’s Apple Watch. Ensure the device is unlocked and discoverable via Bluetooth. (code -27)
[✓] Network resources

• No issues found!`

**Comment by piotr-arkhipenka-m10** [comment]
Hi Nijat! Could you please provide a runnable code snippet to reproduce it?

**Comment by ArkhipenkaPiotr** [comment]
Hi @iamnicat. Could you please provide a runnable code snippet to reproduce it?

**Comment by iamnicat** [comment]
`
class PendingUserTile extends StatefulWidget {
  final bool allDeleted;
  final int index;
  final Function(int) onDeleted;
  final ValueChanged<bool> onSelected;
  const PendingUserTile(
      {super.key,
      required this.allDeleted,
      required this.index,
      required this.onDeleted,
      required this.onSelected});

  @override
  State<PendingUserTile> createState() => _PendingUserTileState();
}

class _PendingUserTileState extends State<PendingUserTile>
    with TickerProviderStateMixin {
  late final AnimationController _controller;
  late final SlidableController _slidableController;
  final _selected = ValueNotifier(false);

  @override
  void initState() {
    _controller = AnimationController(
      vsync: this,
    );

    _slidableController = SlidableController(this);

    super.initState();
  }

  @override
  didUpdateWidget(covariant PendingUserTile oldWidget) {
    if (widget.allDeleted) {
      _slidableController.enableStartActionPane = true;

      _slidableController.openStartActionPane();
    } else {
      _slidableController.close();
      _selected.value = false;
      _slidableController.enableStartActionPane = false;
    }
    super.didUpdateWidget(oldWidget);
  }

  @override
  void didChangeDependencies() {

    if (widget.allDeleted) {
      _slidableController.openStartActionPane();
    } else {
      _slidableController.close();
      _selected.value = false;
    }

    super.didChangeDependencies();
  }

  @override
  void dispose() {
    _controller.dispose();
    _selected.dispose();

    _slidableController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Slidable(
      controller: _slidableController,
      closeOnScroll: !widget.allDeleted,
      endActionPane: ActionPane(
        extentRatio: 0.25,
        motion: const ScrollMotion(),
        children: [
          CustomSlidableAction(
            flex: 7,
            autoClose: false,
            padding: const EdgeInsets.all(0),
            onPressed: (value) {
              widget.onDeleted(widget.index);
            },
            foregroundColor: context.aoneColors.deleteRedColor,
            backgroundColor: context.aoneColors.deleteRedColor!,
            borderRadius: BorderRadius.circular(25),
            child: Padding(
              padding: const EdgeInsets.all(4.0),
              child: Center(
                child: LottieBuilder.asset(
                  'assets/lottie/delete1.json',
                  repeat: false,
                  fit: BoxFit.scaleDown,
                ),
              ),
            ),
          ),
          CustomSlidableAction(
              flex: 1,
              autoClose: false,
              padding: EdgeInsets.zero,
              onPressed: (context) {
                widget.onDeleted(widget.index);
              },
              foregroundColor: const Color(0xfff2f2f7),
              backgroundColor: const Color(0xfff2f2f7),
              borderRadius: BorderRadius.circular(25),
              child: const SizedBox.shrink()),
        ],
      ),
      child: Container(
        margin: const EdgeInsets.symmetric(horizontal: 16),
        padding: const EdgeInsets.symmetric(horizontal: 17, vertical: 20),
        decoration: BoxDecoration(
          color: Color(0xfffefefe),
          borderRadius: BorderRadius.circular(25),
        ),
      ),
    );
  }
}
`


  final _moreClicked = ValueNotifier(false);
  final _items = List.generate(24, (index) => index);
  final _animatedListKey = GlobalKey<AnimatedListState>();
  final _selectedIndex = ValueNotifier<List<int>>([]);
` AnimatedList.separated(
                    key: _animatedListKey,
                    removedSeparatorBuilder: (context, index, animation) =>
                        SizeTransition(
                      sizeFactor: animation,
                      child: const SizedBox(
                        height: 10,
                      ),
                    ),
                    separatorBuilder: (context, index, _) => const SizedBox(
                      height: 10,
                    ),
                    padding: const EdgeInsets.symmetric(vertical: 20).copyWith(
                        top: 20,
                        bottom: MediaQuery.of(context).padding.bottom + 50),
                    initialItemCount: _items.length,
                    itemBuilder: (context, index, animation) {
                      return PendingUserTile(
                        key: ValueKey(_items[index]),
                        index: _items[index],
                        onSelected: (value) {
                          if (value) {
                            _selectedIndex.value.add(index);
                          } else {
                            _selectedIndex.value.remove(index);
                          }
                          if (_selectedIndex.value.length == 1) {
                            _moreClicked.value = true;
                          }
                          if (_selectedIndex.value.isEmpty) {
                            _moreClicked.value = false;
                          }
                        },
                        onDeleted: (p0) {
                          final removed = _items.removeAt(index);
                          _animatedListKey.currentState?.removeItem(
                            index,
                            (context, animation) => Snappable(
                              animation: Animation.fromValueListenable(
                                animation,
                                transformer: (value) => (1 - value).abs(),
                              ),
                              style: const SnappableStyle(
                                particleLifetime:
                                    0.6, // Lifetime of particle before it disappears. Default value is 0.6. Must be between 0.0 and 1.0
                                fadeOutDuration:
                                    0.3, // Duration of fade out animation of particle. Fade out effect starts in particleLifetime - fadeOutDuration and ends when particleLifetime ends. Default value is 0.3. Must be between 0.0 and particleLifetime
                                particleSpeed:
                                    1.0, // Speed of particles. Default value is 1.0
                                particleSize: SnappableParticleSize
                                    .squareFromRelativeWidth(0.005),
                              ),
                              child: SizeTransition(
                                sizeFactor: animation,
                                child: PendingUserTile(
                                  key: Key('local_$index'),
                                  index: removed,
                                  onSelected: (value) {},
                                  onDeleted: (p0) {},
                                  allDeleted: true,
                                ),
                              ),
                            ),
                            duration: const Duration(milliseconds: 500),
                          );
                        },
                        allDeleted: value,
                      );
                    },
                  ),`

**Comment by iamnicat** [comment]
`
  final _moreClicked = ValueNotifier(false);
  final _items = List.generate(24, (index) => index);
  final _animatedListKey = GlobalKey<AnimatedListState>();
  final _selectedIndex = ValueNotifier<List<int>>([]);

 AnimatedList.separated(
                    key: _animatedListKey,
                    removedSeparatorBuilder: (context, index, animation) =>
                        SizeTransition(
                      sizeFactor: animation,
                      child: const SizedBox(
                        height: 10,
                      ),
                    ),
                    separatorBuilder: (context, index, _) => const SizedBox(
                      height: 10,
                    ),
                    padding: const EdgeInsets.symmetric(vertical: 20).copyWith(
                        top: 20,
                        bottom: MediaQuery.of(context).padding.bottom + 50),
                    initialItemCount: _items.length,
                    itemBuilder: (context, index, animation) {
                      return PendingUserTile(
                        key: ValueKey(_items[index]),
                        index: _items[index],
                        onSelected: (value) {
                          if (value) {
                            _selectedIndex.value.add(index);
                          } else {
                            _selectedIndex.value.remove(index);
                          }
                          if (_selectedIndex.value.length == 1) {
                            _moreClicked.value = true;
                          }
                          if (_selectedIndex.value.isEmpty) {
                            _moreClicked.value = false;
                          }
                        },
                        onDeleted: (p0) {
                          final removed = _items.removeAt(index);
                          _animatedListKey.currentState?.removeItem(
                            index,
                            (context, animation) => Snappable(
                              animation: Animation.fromValueListenable(
                                animation,
                                transformer: (value) => (1 - value).abs(),
                              ),
                              style: const SnappableStyle(
                                particleLifetime:
                                    0.6, // Lifetime of particle before it disappears. Default value is 0.6. Must be between 0.0 and 1.0
                                fadeOutDuration:
                                    0.3, // Duration of fade out animation of particle. Fade out effect starts in particleLifetime - fadeOutDuration and ends when particleLifetime ends. Default value is 0.3. Must be between 0.0 and particleLifetime
                                particleSpeed:
                                    1.0, // Speed of particles. Default value is 1.0
                                particleSize: SnappableParticleSize
                                    .squareFromRelativeWidth(0.005),
                              ),
                              child: SizeTransition(
                                sizeFactor: animation,
                                child: PendingUserTile(
                                  key: Key('local_$index'),
                                  index: removed,
                                  onSelected: (value) {},
                                  onDeleted: (p0) {},
                                  allDeleted: true,
                                ),
                              ),
                            ),
                            duration: const Duration(milliseconds: 500),
                          );
                        },
                        allDeleted: value,
                      );
                    },
                  ),`

**Comment by iamnicat** [comment]
Hi @ArkhipenkaPiotr 
You can use your code, just change bg color to white, you will see issue in real device.

https://github.com/user-attachments/assets/8e6cf520-1a70-4219-a4de-ec2ae0d8e994

**Comment by piotr-arkhipenka-m10** [comment]
I fixed this bug ([fix](https://github.com/ArkhipenkaPiotr/thanos_snap_effect/commit/097335a97b84a7380db34ba4d23267315434064b) and it's going to be released in version 0.0.8. @iamnicat Thank you for reporting.

**Comment by ArkhipenkaPiotr** [comment]
I fixed this bug ([fix](https://github.com/ArkhipenkaPiotr/thanos_snap_effect/commit/097335a97b84a7380db34ba4d23267315434064b)) and it's going to be released in version 0.0.8. @iamnicat Thank you for reporting.

**Comment by iamnicat** [comment]
Thanks for quick response @ArkhipenkaPiotr
